apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthra-api
  namespace: anthra
  labels:
    app: anthra-api
    component: api
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anthra-api
  template:
    metadata:
      labels:
        app: anthra-api
        component: api
    spec:
      # TODO: Create custom ServiceAccount with minimal RBAC
      containers:
        - name: api
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          image: anthra/api:v1.42.0@sha256:e39edf7b8d492a2c6e33de78a1f7e09e19cc588efdd61007d04a3fc3ba173a95  # TODO: Pin to specific version tag
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_HOST
              value: anthra-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: anthra
            - name: DB_USER
              value: anthra
            - name: DB_PASSWORD
              value: anthra_default_pass_123  # TODO: Move to K8s Secret
          # TODO: Add securityContext (runAsNonRoot, drop capabilities)
          # TODO: Add resource limits
          # TODO: Add liveness and readiness probes
