apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthra-api
  namespace: anthra
  labels:
    app: anthra-api
    component: api
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anthra-api
  template:
    metadata:
      labels:
        app: anthra-api
        component: api
    spec:
      # TODO: Create custom ServiceAccount with minimal RBAC
      containers:
        - name: api
          image: anthra/api:latest  # TODO: Pin to specific version tag
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_HOST
              value: anthra-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: anthra
            - name: DB_USER
              value: anthra
            - name: DB_PASSWORD
              value: anthra_default_pass_123  # TODO: Move to K8s Secret
          # TODO: Add securityContext (runAsNonRoot, drop capabilities)
          # TODO: Add resource limits
          # TODO: Add liveness and readiness probes
